fix script

diff --git a/build-ffmpeg b/build-ffmpeg
--- a/build-ffmpeg
+++ b/build-ffmpeg
@@ -343,24 +343,33 @@ CONFIGURE_OPTIONS+=("--enable-libvpx")
 if command_exists "python3"; then
   # dav1d needs meson and ninja along with nasm to be built
   if command_exists "pip3"; then
-    needPip=false
+    needMesonOrNinja=false
     for r in meson ninja; do
       if ! command_exists ${r}; then
-        needPip=true
+        needMesonOrNinja=true
       fi
     done
 
-    if $needPip; then
-      # needInstall and ninja can be installed via pip3
-      execute pip3 install pip setuptools --quiet --upgrade --no-cache-dir --disable-pip-version-check
+    if $needMesonOrNinja; then
+      if [[ "$OSTYPE" == "darwin"* ]]; then
+        #check if macOs and brew is available, use it
+        if command_exists "brew"; then
+          brew install python-setuptools meson ninja
+        else
+          echo 'Could not install meson and ninja'
+        fi
+      else
+        # meson and ninja can be installed via pip3
+        execute pip3 install pip setuptools --quiet --upgrade --no-cache-dir --disable-pip-version-check
+
+        for r in meson ninja; do
+          if ! command_exists ${r}; then
+            execute pip3 install ${r} --quiet --upgrade --no-cache-dir --disable-pip-version-check
+          fi
+          export PATH=$PATH:~/Library/Python/3.9/bin
+        done
+      fi
     fi
-
-    for r in meson ninja; do
-      if ! command_exists ${r}; then
-        execute pip3 install ${r} --quiet --upgrade --no-cache-dir --disable-pip-version-check
-      fi
-      export PATH=$PATH:~/Library/Python/3.9/bin
-    done
   fi
   if command_exists "meson"; then
     if build "dav1d" "1.1.0"; then
